### ISSUE TITLE
Feature Request Review

### ISSUE THREAD

**Issue by mp1pro** [haldunanil/bwa-u4-feature-request#1]
Allowing users to preview the tracks is a great idea. That will improve the apps efficiency and user interface. Creating the new 'Player' component for this feature is the correct approach. Very nice using a third party plugins to run the player. Using the react-grid-system will make the development process faster. Isolating the play/pause method from the user clicking on a song makes the app more granular and modular. The technical design is well layed out. I would suggest adding all the suggested features and go in for the over kill. Very good feature request.

**Comment by haldunanil** [comment]
Thanks Marvin!
